### PR TITLE
Icon Updates

### PR DESCRIPTION
**Pull request by dgibbs64**
Hey,

I am the developer of LinuxGSM and HLSW-Fixes. I see it is now possible to add icons to SAT which is great. I will be adding a whole bunch of icons using steamdb.info. They are the same icons I used for updating and adding more games to HLSW. I think that SAT will be a great replacement for the not long in the tooth HLSW.

I have created a pull request to make you aware of my fork. You are welcome to merge now or wait. Feel free to test etc.

Hope this helps.

### CODE REVIEW

**Comment by Drifter321** [comment]
There is a typo in the csgo image name. I'm ok with the changes however, I think they should still be embedded into the exe like the old ones. That way even if you override the image you can still keep the original.

**Comment by dgibbs64** [comment]
Awesome. I agree embedding them in to the executive would be great. I however have no programming skills when it comes to this. So i can either provide the icons like i am and you can embed then yourself or you can tell me how to do it and I will have a go myself :-).

**Comment by dgibbs64** [comment]
Another note is that the logos come in .ico format on steamdb.info. The ico supports many different sizes. This might be a great feature for future development allowing the option to select a much higher res logo in the ico file. Plus it will save a lot of time as there is no requirement to convert the ico file to png.

See example https://steamdb.info/app/447820/info/ "clienticon" if you open up the ico file in gimp you can see there are various different sizes embedded in to the ico file.

**Comment by Drifter321** [comment]
To make them embed you need to specify the path in the mapping correctly (how it currently is) and then you define your images in the icons.qrc file. Just remove any unused images and add your files to the file.

**Comment by dgibbs64** [comment]
I have completed the changes for embedding icons.

**Comment by Drifter321** [comment]
Thanks!

**Pull request merged**
